name: Build, Publish, and Code Sign DummyWebApp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.x'

    - name: Restore dependencies
      run: dotnet restore src/DummyWebApp.csproj

    - name: Build project
      run: dotnet build src/DummyWebApp.csproj --configuration Release

    - name: Publish web app
      run: dotnet publish src/DummyWebApp.csproj --configuration Release --output src/publish

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: src/publish/

  sign:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: artifacts/

    - name: Create self-signed certificate and sign DLL
      shell: pwsh
      run: |
        $cert = New-SelfSignedCertificate -Type CodeSigning -Subject "CN=DummyWebAppPOC" -CertStoreLocation "Cert:\CurrentUser\My"
        $pfxPath = "$env:RUNNER_TEMP\dummywebapp.pfx"
        $password = ConvertTo-SecureString -String "P@ssw0rd!" -Force -AsPlainText
        Export-PfxCertificate -Cert $cert -FilePath $pfxPath -Password $password
        $dllPath = "artifacts\DummyWebApp.dll"
        & "C:\Program Files (x86)\Windows Kits\10\bin\x64\signtool.exe" sign /f $pfxPath /p "P@ssw0rd!" /fd SHA256 $dllPath

    - name: Upload signed artifacts
      uses: actions/upload-artifact@v4
      with:
        name: signed-artifacts
        path: artifacts/